/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Monitor;

import java.nio.file.Path;
import java.nio.file.Paths;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;



public class App {

    private static Logger loggerTest1 = LoggerFactory.getLogger("Monitor.test1");
    private static Logger loggerTest2 = LoggerFactory.getLogger("Monitor.test2");
    private static Logger loggerTest3 = LoggerFactory.getLogger("Monitor.test2.sun");
    private static Logger loggerTest4 = LoggerFactory.getLogger("Monitor.test1.sun");

    public static void main(String[] args) {
        loggerTest1.info("test1");
        loggerTest2.info("test2");
        loggerTest3.info("test3");
        loggerTest4.info("test4");

        SampleThread1 thread1 = new SampleThread1();
        Runtime.getRuntime().addShutdownHook(new ShutdownThread(thread1));

        Path p1 = Paths.get("");
        Path p2 = p1.toAbsolutePath();
        //System.out.println(App.class.getResource("/Config").getPath());
        System.out.println(java.lang.management.ManagementFactory.getRuntimeMXBean().getName().split("@")[0]);

        thread1.start();
    }
}
