/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Monitor;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

public class App {
    private static final Logger LOGGER = LogManager.getLogger();

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        SampleThread1 thread1 = new SampleThread1();
        LOGGER.info("logテスト");
        LOGGER.error("logテスト");
        Runtime.getRuntime().addShutdownHook(new ShutdownThread(thread1));

        thread1.start();
    }
}
